spring:
  sns:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client:
        id: {id}
        secret: {secret}
      token:
        url: https://oauth2.googleapis.com/token
      user:
        url: https://www.googleapis.com/oauth2/v1/userinfo

    naver:
      url: https://nid.naver.com/oauth2.0/authorize
      client:
        id: {id}
        secret: {secret}
      token:
        url: https://nid.naver.com/oauth2.0/token
      user:
        url: https://openapi.naver.com/v1/nid/me

    github:
      url: https://github.com/login/oauth/authorize
      client:
        id: {id}
        secret: {secret}
      token:
        url: https://github.com/login/oauth/access_token
      user:
        url: https://api.github.com/user
